export class Brands {
    static BRANDS = 
        [
            "Alfa Romeo",
            "Aston Martin",
            "Audi",
            "Baic",
            "Brillance",
            "BMW",
            "Bugatti",
            "BYD",
            "Cadillac",
            "Chana",
            "Changan",
            "Chery",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Corvette",
            "Dacia",
            "Daewoo",
            "Daihatsu",
            "DFM",
            "DFSK",
            "Dodge",
            "DS",
            "Emgrand",
            "Faw",
            "Ferrari",
            "Fiat",
            "Fiat Professional",
            "Ford",
            "FOTON",
            "Geely",
            "Gonow",
            "Great wall",
            "Hafei motors",
            "Haima",
            "Honda",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Iran Khodro",
            "Isuzu",
            "JAC",
            "Jaguar",
            "Jeep",
            "JMC",
            "Kia",
            "Lada",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Lexus",
            "Lifan",
            "Mahindra",
            "Maserati",
            "Mazda",
            "McLaren",
            "Mercedes",
            "MG",
            "Mini",
            "Mitsubishi",
            "Nissan",
            "Opel",
            "Peugeot",
            "Porshe",
            "Renault",
            "Rolls Royce",
            "Rover",
            "Saab",
            "Saipa",
            "Seat",
            "Skoda",
            "Smart",
            "SsangYong",
            "Subaru",
            "Suzuki",
            "Tata",
            "Toyota",
            "Volkswagen",
            "Volvo",
            "Zotye",
            "Autre"

        ]
}